name: 'NPM install'
description: 'Installs dependencies through npm or gets them from the cache'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./web/node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      working-directory: ./
      shell: bash
